### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by herzog31** [hlxsites/asprey#46]
- [x] Implement searchbar in navigation
- [x] Create dedicated search page (empty for now).
- [x] On submit, the searchbar redirects to the results page (e.g. `/gb/en/search.html?search_query=pen`)

**Comment by hannessolo** [comment]
Implemented by #35 

See https://main--asprey--hlxsites.hlx.live/gb/en/search?search_query=pen

**Comment by hannessolo** [comment]
@herzog31 Thanks, forgot about that. Will open a new PR to fix it. For now it can be closed by clicking the background area.

**Comment by hannessolo** [comment]
See #65
