### ISSUE TITLE
Provide access to AEM environment with production content

### ISSUE THREAD

**Issue by herzog31** [hlxsites/asprey#52]
- [ ] Provide read access for Franklin engineers to AEM environment with production content
    - [ ] Hannes Hertach
    - [ ] Luca Adams
    - [ ] Jean-Christophe Kautzmann
    - [ ] Alexandru-Cosmin Vlajoaga
    - [ ] Mark J. Becker
- Primary contacts: Alisha & Jonathan
- Understand content structure
- Enable importing of enrichment content (Experience Fragments & Content Fragments)

**Comment by jonathanclarey** [comment]
Hi Mark, please can you provide emails for these users?

**Comment by jonathanclarey** [comment]
Hi Mark, everyone should now have received a notification with access to DEV author on AEM.
