### ISSUE TITLE
Migrate Customer Care Pages

### ISSUE THREAD

**Issue by herzog31** [hlxsites/asprey#57]
This applies to the following pages:
* https://www.asprey.com/gb/en/customer-care/book-an-appointment-in-store.html
* https://www.asprey.com/gb/en/customer-care/delivery-return.html
* https://www.asprey.com/gb/en/customer-care/personalisation.html
* https://www.asprey.com/gb/en/customer-care/faqs.html
* https://www.asprey.com/gb/en/customer-care/contact.html
* https://www.asprey.com/gb/en/client-services/leather-care.html
* https://www.asprey.com/gb/en/client-services/leather-skins.html
* https://www.asprey.com/gb/en/client-services/special-commissions.html
* https://www.asprey.com/gb/en/asprey-cites.html

- [ ] Documents are already imported to Sharepoint, but feel free to simplify the content structure
- [ ] Link pages in footer.docx document
- [ ] Mini navigation block
    - ![image](https://github.com/hlxsites/asprey/assets/4084418/109eaaf6-b3e2-416e-8372-f3b46d066cba)
- [ ] Table block
    - ![image](https://github.com/hlxsites/asprey/assets/4084418/a2ec7925-2826-4b1a-99d5-f72f5db90dac)
- [ ] Please update the importer to reflect your content changes. Make sure it's reviewed by the whole team so it does not impact other content pages in an inconsistent way.

**Comment by hannessolo** [comment]
FYI @vlajoaga added 3 pages: 

* https://www.asprey.com/gb/en/client-services/leather-care.html
* https://www.asprey.com/gb/en/client-services/leather-skins.html
* https://www.asprey.com/gb/en/client-services/special-commissions.html

**Comment by herzog31** [comment]
@hannessolo don't forget about https://www.asprey.com/gb/en/customer-care/find-a-boutique.html
